# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/nmearl/projects/glue-genomics-viewers/glue_genomics_viewers/viewers/network/qt/viewer_state.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Layout(object):
    def setupUi(self, Layout):
        Layout.setObjectName("Layout")
        Layout.resize(496, 291)
        self.formLayout = QtWidgets.QFormLayout(Layout)
        self.formLayout.setObjectName("formLayout")
        self.layout_label = QtWidgets.QLabel(Layout)
        self.layout_label.setObjectName("layout_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.layout_label)
        self.combosel_layout = QtWidgets.QComboBox(Layout)
        self.combosel_layout.setObjectName("combosel_layout")
        self.combosel_layout.addItem("")
        self.combosel_layout.addItem("")
        self.combosel_layout.addItem("")
        self.combosel_layout.addItem("")
        self.combosel_layout.addItem("")
        self.combosel_layout.addItem("")
        self.combosel_layout.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combosel_layout)

        self.retranslateUi(Layout)
        QtCore.QMetaObject.connectSlotsByName(Layout)

    def retranslateUi(self, Layout):
        _translate = QtCore.QCoreApplication.translate
        Layout.setWindowTitle(_translate("Layout", "Form"))
        self.layout_label.setText(_translate("Layout", "Layout"))
        self.combosel_layout.setItemText(0, _translate("Layout", "Default"))
        self.combosel_layout.setItemText(1, _translate("Layout", "Circular"))
        self.combosel_layout.setItemText(2, _translate("Layout", "Kamada Kawaii"))
        self.combosel_layout.setItemText(3, _translate("Layout", "Planar"))
        self.combosel_layout.setItemText(4, _translate("Layout", "Spectral"))
        self.combosel_layout.setItemText(5, _translate("Layout", "Spring"))
        self.combosel_layout.setItemText(6, _translate("Layout", "Shell"))
